"""Target-analysis report generator.

Reads pilot Performance snapshots plus the derived-targets artifact and writes
``docs/target_analysis_report.md`` containing the required diagnostics as
tables and ASCII distributions (no plotting dependency is required).
"""

from __future__ import annotations

import json
import math
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import cast

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from tiktok_analytics_factory.targets.build import DEFAULT_CONFIG
from tiktok_analytics_factory.targets.construct import sample_pairwise

SNAP_ROOT = Path("data/pilot/snapshots")
ARTIFACT = Path("data/pilot/performance_targets_v0_1.json")
REPORT = Path("docs/target_analysis_report.md")


def ascii_hist(values: list[float], bins: int = 8, width: int = 40) -> list[str]:
    if not values:
        return ["(no data)"]
    lo, hi = min(values), max(values)
    if lo == hi:
        return [f"single value {lo:.3f}"]
    counts = [0] * bins
    for v in values:
        idx = min(bins - 1, int((v - lo) / (hi - lo) * bins))
        counts[idx] += 1
    peak = max(counts)
    lines = []
    for i, c in enumerate(counts):
        bar = "#" * max(0, round(c / peak * width))
        edge = lo + (hi - lo) * i / bins
        lines.append(f"{edge:9.2f} | {bar} {c}")
    return lines


def pearson(xs: list[float], ys: list[float]) -> float:
    n = len(xs)
    if n < 2:
        return float("nan")
    mx, my = sum(xs) / n, sum(ys) / n
    sxx = sum((x - mx) ** 2 for x in xs)
    syy = sum((y - my) ** 2 for y in ys)
    if sxx == 0 or syy == 0:
        return float("nan")
    return sum((x - mx) * (y - my) for x, y in zip(xs, ys)) / math.sqrt(sxx * syy)


def main() -> int:
    artifact = json.loads(ARTIFACT.read_text(encoding="utf-8"))
    recs = artifact["records"]

    snapshots = [
        json.loads(p.read_text(encoding="utf-8"))
        for p in sorted(SNAP_ROOT.glob("*/metadata.normalized*.json"))
    ]
    per_video = Counter(s["video_id"] for s in snapshots)

    lines: list[str] = []
    w = lines.append
    w("# Pilot target analysis report (`performance_target_v0_1`)")
    w("")
    w(f"- Derived artifact: `{ARTIFACT}`")
    w(f"- Target version: `{artifact['target_version']}`")
    w(f"- Constructed at: {artifact['constructed_at']}")
    w("- Snapshot source: `data/pilot/snapshots/` (synthetic stand-ins generated by")
    w("  `scripts/make_pilot_snapshots.py` because the issue #8 pilot snapshots were")
    w(
        "  not present in this worktree; field names follow `NormalizedMetadata` exactly."
    )
    w("  Replace with real pilot snapshots before finalizing the primary target.)")
    w("")

    n = len(recs)
    w("## Availability on the pilot set")
    w("")
    w("| quantity | available | rate |")
    w("|---|---|---|")
    for field in ("published_at", "observed_at", "creator_key", "views", "likes"):
        k = sum(1 for r in recs if r[field] is not None)
        w(f"| `{field}` | {k}/{n} | {k / n:.0%} |")
    sum(1 for r in recs if r["creator_key"] is not None)
    w(
        "`follower_count` is **not present** in Performance snapshots (field does not exist in NormalizedMetadata), so follower-based normalization is infeasible; creator-relative baselines are used instead."
    )
    w("")
    ages = sorted(r["post_age_days"] for r in recs if r["post_age_days"] is not None)
    w(
        f"Post age at observation (days): min={ages[0]:.2f} median={sorted(ages)[len(ages) // 2]:.2f} max={ages[-1]:.2f} over {len(ages)} records."
    )
    w("")
    per_creator = Counter(r["creator_key"] for r in recs if r["creator_key"])
    w(
        "Videos per creator: "
        + ", ".join(f"{k}={v}" for k, v in sorted(per_creator.items()))
    )
    w("")
    rep = sum(1 for v, c in per_video.items() if c > 1)
    w(f"Videos with more than one Performance snapshot (repeated observation): {rep}.")
    w("Because repeated snapshots are essentially absent, fixed-age snapshot policy 1")
    w("is infeasible; policy 2 (explicit age adjustment) is applied — see")
    w("docs/performance_target.md#snapshot-age-policy.")
    w("")

    valid = [r for r in recs if r["is_valid"]]
    w("## Raw metric relationships (valid records)")
    w("")
    lv = [r["log_views"] for r in valid]
    pairs: dict[str, float] = {
        "log_views vs log(post_age_days)": pearson(
            lv, [math.log(r["post_age_days"]) for r in valid]
        ),
        "log_views vs likes_per_view": pearson(
            lv, [r["likes_per_view"] for r in valid]
        ),
        "likes vs comments (raw)": pearson(
            [float(r["likes"]) for r in valid], [float(r["comments"]) for r in valid]
        ),
        "creator_relative_log_views vs log(post_age_days)": pearson(
            [r["creator_relative_log_views"] for r in valid],
            [math.log(r["post_age_days"]) for r in valid],
        ),
    }
    w("| relationship | Pearson r |")
    w("|---|---|")
    for name, r_val in pairs.items():
        w(
            f"| {name} | {r_val:+.3f} |"
            if not math.isnan(r_val)
            else f"| {name} | n/a |"
        )
    w("")
    big = [r for r in valid if r["log_views"] > sorted(lv)[int(0.95 * len(lv))]]
    w(
        f"Outliers (top 5% of log_views): {', '.join(r['video_id'][-4:] for r in big)} "
        f"(max views = {max(r['views'] for r in valid)})."
    )
    w("")

    w("## Diagnostic: raw views / log views vs post age and creator baseline")
    w("")
    w("log_views by post-age bucket:")
    w("```")
    buckets: dict[str, list[float]] = defaultdict(list)
    for r in valid:
        b = (
            "<7d"
            if r["post_age_days"] < 7
            else ("7-60d" if r["post_age_days"] < 60 else ">=60d")
        )
        buckets[b].append(r["log_views"])
    for b in ("<7d", "7-60d", ">=60d"):
        vs = buckets.get(b, [])
        m = sum(vs) / len(vs) if vs else float("nan")
        w(f"{b:>6}: n={len(vs):2d} mean log_views={m:.2f}")
    w("```")
    w("")
    w("Distribution of `log_views`:")
    w("```")
    lines.extend([])
    hist_lv = ascii_hist(lv)
    w("\n".join(hist_lv))
    w("```")

    tgt = [r["creator_relative_log_views"] for r in valid]
    w("")
    w("## Chosen primary target: `creator_relative_log_views`")
    w("")
    w(
        "Definition: `log1p(video_views) - median(log1p(views of creator's OTHER videos))`"
    )
    w("(strict leave-one-out; requires >= 2 other valid videos).")
    w("")
    w(
        f"Coverage: {len(tgt)}/{n} valid ({len(tgt) / n:.0%}); invalid reasons: {artifact['invalid_reason_counts']}"
    )
    w("")
    w("Distribution:")
    w("```")
    w("\n".join(ascii_hist(tgt)))
    w("```")
    w("")
    w("Target vs post-age bucket (reduced exposure dependence check):")
    w("```")
    tb: dict[str, list[float]] = defaultdict(list)
    for r in valid:
        b = (
            "<7d"
            if r["post_age_days"] < 7
            else ("7-60d" if r["post_age_days"] < 60 else ">=60d")
        )
        tb[b].append(r["creator_relative_log_views"])
    for b in ("<7d", "7-60d", ">=60d"):
        vs = tb.get(b, [])
        m = sum(vs) / len(vs) if vs else float("nan")
        w(f"{b:>6}: n={len(vs):2d} mean target={m:+.2f}")
    w("```")
    w("")
    w(
        "Target vs creator baseline level (should be ~flat; slope shown via correlation):"
    )
    w(
        f"corr(target, creator_baseline_log_views) = "
        f"{pearson(tgt, [r['creator_baseline_log_views'] for r in valid]):+.3f}"
    )
    w("")

    w("## Sensitivity to alternative normalization choices")
    w("")
    w("| variant | coverage | corr with log(post_age_days) |")
    w("|---|---|---|")
    from tiktok_analytics_factory.targets.construct import creator_relative_log_views

    for min_others in (1, 2, 3):
        vals = {}
        for r in recs:
            sibs = [
                o
                for o in recs
                if o["creator_key"]
                and o["creator_key"] == r["creator_key"]
                and o["video_id"] != r["video_id"]
            ]
            rel, _, _ = creator_relative_log_views(
                video_id=r["video_id"],
                views=r["views"],
                sibling_observations=sibs,
                min_other_videos=min_others,
            )
            if rel is not None:
                vals[r["video_id"]] = (rel, math.log(r["post_age_days"]))
        xs = [v[0] for v in vals.values()]
        ys = [v[1] for v in vals.values()]
        c = pearson(xs, ys)
        w(
            f"| min_other_videos={min_others} | {len(vals)}/{n} | {c:+.3f} |"
            if not math.isnan(c)
            else f"| min_other_videos={min_others} | {len(vals)}/{n} | n/a |"
        )
    res = [
        (r["performance_residual"], math.log(r["post_age_days"]))
        for r in valid
        if r["performance_residual"] is not None
    ]
    cr = pearson([x[0] for x in res], [x[1] for x in res]) if res else float("nan")
    w(
        f"| performance_residual (age-adjusted) | {len(res)}/{n} | "
        + (f"{cr:+.3f} |" if not math.isnan(cr) else "n/a |")
    )
    lv_corr = pairs["log_views vs log(post_age_days)"]
    w(f"| log_views baseline (diagnostic A) | {len(valid)}/{n} | {lv_corr:+.3f} |")
    w("")

    margin = cast(float, DEFAULT_CONFIG["pairwise_margin_log_units"])
    pw_records = [
        {
            "video_id": r["video_id"],
            "comparability_key": r["creator_key"],
            "target_value": r["creator_relative_log_views"],
        }
        for r in valid
    ]
    pairs_out = sample_pairwise(pw_records, margin=margin)
    counts = Counter(p["label"] for p in pairs_out)
    w(f"## Pairwise class balance (comparable within creator, margin={margin})")
    w("")
    w(f"Sampled pairs (cap 5/video, seed 0): {len(pairs_out)}")
    w("")
    w("| label | count | share |")
    w("|---|---|---|")
    total = max(1, len(pairs_out))
    for lbl in ("a_gt_b", "b_gt_a", "tie"):
        w(f"| {lbl} | {counts.get(lbl, 0)} | {counts.get(lbl, 0) / total:.0%} |")
    w("")

    w("## Age-adjusted residual model")
    w("")
    m = artifact.get("age_baseline_model")
    if m:
        w(
            "Fitted OLS coefficients (`log1p(views) ~ intercept + log(post_age_days) + creator_baseline`):"
        )
        w("")
        w("```json")
        w(json.dumps(m, indent=2))
        w("```")
    else:
        w(
            "Model could not be fit on this pilot set (documented explicitly in the artifact);"
        )
        w(
            "`performance_residual` is therefore null where no prediction exists — never imputed."
        )
    w("")
    w("## Conclusion")
    w("")
    base_corr = pearson(tgt, [r["creator_baseline_log_views"] for r in valid])
    w(
        "Primary target selected (PROVISIONAL): "
        "**`creator_relative_log_views` @ `performance_target_v0_1`**."
    )
    w("Rationale: highest coverage among exposure-corrected candidates, robust to")
    w("the extreme view outlier (median-based baseline), interpretable in log units,")
    w("usable for both pointwise and within-creator pairwise labels.")
    w(f"Caveats on this pilot set: corr(target, creator baseline) = {base_corr:+.3f}")
    w("(with n=16 this is not distinguishable from the mechanical coupling between a")
    w("leave-one-out residual and its small sibling pool); the age-adjusted residual")
    w("model fits poorly (see R^2 above), so `performance_residual` remains secondary")
    w("until real repeated-snapshot data from issue #8 supports a better age model.")
    w("")
    w("**Status: exploratory.** Snapshots here are synthetic stand-ins; final")
    w("primary-target selection and coverage numbers must be re-confirmed on real")
    w("issue #8 pilot snapshots before dataset freeze.")
    w("")
    n_valid = sum(1 for r in recs if r["is_valid"])
    w("## Completion note")
    w("")
    w("primary_target=creator_relative_log_views@performance_target_v0_1")
    w(f"target_coverage_on_pilot={n_valid}/{n} valid ({100 * n_valid / n:.0f}%)")
    w(
        "biggest_remaining_bias=targets derive from a single observation per video "
        "with widely varying post ages; the age-adjusted residual target exists but "
        "its baseline model is fit on very few rows from synthetic stand-in snapshots, "
        "so residual exposure bias is not fully removed until real repeated-snapshot "
        "pilot data replaces `scripts/make_pilot_snapshots.py` output."
    )
    w("")

    REPORT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {REPORT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
